<div style="position:relative;">
	<?php
		$this->headLink()->appendStylesheet($this->assetUrl('css/columns.css', 'Column Maker'));
		?>

	<?php
	foreach ($perpages as $perpage){
		echo "<div class='column' style='background-color: white;'>";
		echo "<div class='unit_img_outer no_text spacing_21 border_1 first_col'>";
		echo	"<div class='column-header'>";
		echo		"<p class='column-header-text'> GROW YOURSELF </p>";
		echo	"</div>";
		echo	"<a class='region' href='https://google.com'>";
		echo		"<span class='unit_img_inner'>";
		echo			"<img alt='Night Gallery' width='280' height='224' src='https://www.exhibit-e.com/imgs/Screen_Shot_2018_03_13_at_5_04_14_PM0.png'/>";
		echo		"</span>";
		echo		"<span class='column-body-title'>";
		echo			"Individual";
		echo		"</span>";
		echo		"<span class='column-body-content'>";
		echo			 "To see a World in a Grain of Sand";
		echo				"And a Heaven in a Wild Flower,";
		echo				"Hold Infinity in the palm of your hand";
		echo				"And Eternity in an hour.";
		echo		"</span>";
		echo	"</a>";
		echo	"<div class='pointer-button' id='pointer'>VIEW MORE</div>";
		echo "</div>";
	echo "</div>";
	}
	?>

	<p> Anyone there? </p>

</div>